{% set version = "3.5.5" %}

package:
  name: python
  version: {{ version }}

source:
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  md5: 7c825b747d25c11e669e99b912398585
  patches:
    - omit-local-site-packages.patch  # [osx]
    - osx64-dist.patch                # [osx and x86_64]
    - win-find_exe.patch              # [win]
    - win-library_bin.patch           # [win]
    # Adjust FD_SETSIZE to allow select() to wait on more connections
    # simultaneously.  Desirable for serious use of Tornado on Windows.
    # See also:
    # - https://bugs.python.org/issue28708
    # - https://github.com/zeromq/libzmq/issues/1165
    - fd_setsize.patch                # [win]
    - mingw-w64--DMS_WINXX.patch
    - win-msc_ver-1900.patch
    - 0017-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch

build:
  number: 2
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.5     # [unix]
  script_env:
    - python_branding
  skip: True            # [win and vc != 14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bzip2  # [unix]
    - sqlite  # [unix]
    - xz  # [unix]
    - zlib  # [unix]
    - openssl  # [unix]
    - readline  # [unix]
    - tk  # [unix]
    - ncurses  # [unix]
    - libffi  # [unix]
  run:
    - bzip2  # [unix]
    - sqlite  # [unix]
    - xz  # [unix]
    - zlib  # [unix]
    - openssl  # [unix]
    - readline  # [unix]
    - tk  # [unix]
    - ncurses  # [unix]
    - libffi  # [unix]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    -  _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"  # [linux64]

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - pelson
    - ocefpaf
